### ISSUE TITLE
Error: Undefined class constant 'READ_LATEST'

### ISSUE THREAD

**Issue by supertassu** [hallowelt/mwstake-mediawiki-component-contentprovisioner#11]
Hi. Seeing this on Wikimedia CI for some extensions:
```
17:34:18 [833e2102f9030fb72a7a009d] [no req]   Error: Undefined class constant 'READ_LATEST'
17:34:18 Backtrace:
17:34:18 from /workspace/src/vendor/mwstake/mediawiki-component-contentprovisioner/src/ContentProvisioner/DefaultContentProvisioner.php(221)
17:34:18 #0 /workspace/src/vendor/mwstake/mediawiki-component-contentprovisioner/src/ContentProvisioner/DefaultContentProvisioner.php(157): MWStake\MediaWiki\Component\ContentProvisioner\ContentProvisioner\DefaultContentProvisioner->processManifestFile()
17:34:18 #1 /workspace/src/vendor/mwstake/mediawiki-component-contentprovisioner/src/ContentProvisionerPipeline.php(133): MWStake\MediaWiki\Component\ContentProvisioner\ContentProvisioner\DefaultContentProvisioner->provision()
17:34:18 #2 /workspace/src/vendor/mwstake/mediawiki-component-contentprovisioner/src/MediaWiki/Maintenance/ProvisionContents.php(33): MWStake\MediaWiki\Component\ContentProvisioner\ContentProvisionerPipeline->execute()
17:34:18 #3 /workspace/src/maintenance/includes/LoggedUpdateMaintenance.php(49): MWStake\MediaWiki\Component\ContentProvisioner\MediaWiki\Maintenance\ProvisionContents->doDBUpdates()
17:34:18 #4 /workspace/src/maintenance/update.php(201): LoggedUpdateMaintenance->execute()
17:34:18 #5 /workspace/src/maintenance/includes/MaintenanceRunner.php(698): UpdateMediaWiki->execute()
17:34:18 #6 /workspace/src/maintenance/doMaintenance.php(100): MediaWiki\Maintenance\MaintenanceRunner->run()
17:34:18 #7 /workspace/src/maintenance/update.php(302): require_once(string)
17:34:18 #8 {main}
```
Seems to be caused by <https://lists.wikimedia.org/hyperkitty/list/wikitech-l@lists.wikimedia.org/thread/GPY6KERHONBW7F6D5WHVK4XIAQWEVT4G/>, and should be quite easy to fix even in a way that's compatible with older MW versions.

**Comment by HamishSlater** [comment]
Use IDBAccessObject constants
https://github.com/hallowelt/mwstake-mediawiki-component-contentprovisioner/commit/88f7fc0f9bf6cc3047a82d8fdca5b8afd1ca4ce4
